    public class AgentService
    {
        public List<Agent> GetAgents()
        {
            return new List<Agent>
            {
                new Agent { Name="ada", Image="images/agents/ada.png" },
                new Agent { Name="arcadia", Image="images/agents/arcadia.png" },
                new Agent { Name="artemis", Image="images/agents/artemis.png" },
                new Agent { Name="asuri", Image="images/agents/asuri.png" },
                new Agent { Name="azoth", Image="images/agents/azoth.png" },
                new Agent { Name="barraza", Image="images/agents/barraza.png" },
                new Agent { Name="bodvar", Image="images/agents/bodvar.png" },
                new Agent { Name="brynn", Image="images/agents/brynn.png" },
                new Agent { Name="caspian", Image="images/agents/caspian.png" },
                new Agent { Name="cassidy", Image="images/agents/cassidy.png" },
                new Agent { Name="cross", Image="images/agents/cross.png" },
                new Agent { Name="diana", Image="images/agents/diana.png" },
                new Agent { Name="dusk", Image="images/agents/dusk.png" },
                new Agent { Name="ember", Image="images/agents/ember.png" },
                new Agent { Name="ezio", Image="images/agents/ezio.png" },
                new Agent { Name="fait", Image="images/agents/fait.png" },
                new Agent { Name="gnash", Image="images/agents/gnash.png" },
                new Agent { Name="hattori", Image="images/agents/hattori.png" },
                new Agent { Name="imgui", Image="images/agents/imgui.png" },
                new Agent { Name="isaiah", Image="images/agents/isaiah.png" },
                new Agent { Name="jaeyun", Image="images/agents/jaeyun.png" },
                new Agent { Name="jhala", Image="images/agents/jhala.png" },
                new Agent { Name="jiro", Image="images/agents/jiro.png" },
                new Agent { Name="kaya", Image="images/agents/kaya.png" },
                new Agent { Name="koji", Image="images/agents/koji.png" },
                new Agent { Name="kor", Image="images/agents/kor.png" },
                new Agent { Name="ladyvera", Image="images/agents/ladyvera.png" },
                new Agent { Name="linfei", Image="images/agents/linfei.png" },
                new Agent { Name="loki", Image="images/agents/loki.png" },
                new Agent { Name="lucien", Image="images/agents/lucien.png" },
                new Agent { Name="magyar", Image="images/agents/magyar.png" },
                new Agent { Name="mako", Image="images/agents/mako.png" },
                new Agent { Name="mirage", Image="images/agents/mirage.png" },
                new Agent { Name="mordex", Image="images/agents/mordex.png" },
                new Agent { Name="munin", Image="images/agents/munin.png" },
                new Agent { Name="nai", Image="images/agents/nai.png" },
                new Agent { Name="nix", Image="images/agents/nix.png" },
                new Agent { Name="onyx", Image="images/agents/onyx.png" },
                new Agent { Name="orion", Image="images/agents/orion.png" },
                new Agent { Name="petra", Image="images/agents/petra.png" },
                new Agent { Name="priya", Image="images/agents/priya.png" },
                new Agent { Name="ragnir", Image="images/agents/ragnir.png" },
                new Agent { Name="ransom", Image="images/agents/ransom.png" },
                new Agent { Name="raptor", Image="images/agents/raptor.png" },
                new Agent { Name="rayman", Image="images/agents/rayman.png" },
                new Agent { Name="reno", Image="images/agents/reno.png" },
                new Agent { Name="roland", Image="images/agents/roland.png" },
                new Agent { Name="rupture", Image="images/agents/rupture.png" },
                new Agent { Name="scarlet", Image="images/agents/scarlet.png" },
                new Agent { Name="sentinel", Image="images/agents/sentinel.png" },
                new Agent { Name="seven", Image="images/agents/seven.png" },
                new Agent { Name="sidra", Image="images/agents/sidra.png" },
                new Agent { Name="teros", Image="images/agents/teros.png" },
                new Agent { Name="tezca", Image="images/agents/tezca.png" },
                new Agent { Name="thatch", Image="images/agents/thatch.png" },
                new Agent { Name="thea", Image="images/agents/thea.png" },
                new Agent { Name="thor", Image="images/agents/thor.png" },
                new Agent { Name="ulgrim", Image="images/agents/ulgrim.png" },
                new Agent { Name="val", Image="images/agents/val.png" },
                new Agent { Name="vector", Image="images/agents/vector.png" },
                new Agent { Name="vivi", Image="images/agents/vivi.png" },
                new Agent { Name="volkov", Image="images/agents/volkov.png" },
                new Agent { Name="vraxx", Image="images/agents/vraxx.png" },
                new Agent { Name="wushang", Image="images/agents/wushang.png" },
                new Agent { Name="xull", Image="images/agents/xull.png" },
                new Agent { Name="yumiko", Image="images/agents/yumiko.png" },
                new Agent { Name="zariel", Image="images/agents/zariel.png" },
                new Agent { Name="zuva", Image="images/agents/zuva.png" }
            };
        }
    }
